### ISSUE TITLE
No github icon on card

### ISSUE THREAD

**Issue by Fahrenhei7** [gambala/trello#3]
![screenshot_20161001_223506](https://cloud.githubusercontent.com/assets/10668780/19016601/61b3fa8a-8827-11e6-88f2-b58946626eb8.png)
-------
![screenshot_20161001_223605](https://cloud.githubusercontent.com/assets/10668780/19016604/74f92188-8827-11e6-9307-b1d27617acca.png)

**Comment by gambala** [comment]
How can I get those github counters? Trello power-up, third-party extension?

**Comment by Fahrenhei7** [comment]
Trello power up for teams
